security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/
            anonymous: true
            oauth:
                resource_owners:
                    vkontakte:           "/login/check-vkontakte"
#                        facebook:           "/login/check-facebook"
#                        google:             "/login/check-google"
#                        my_custom_provider: "/login/check-custom"
#                        my_github:          "/login/check-github"
                login_path:        /connect/vkontakte
                use_forward:       true
                failure_path:      /connect
                provider: fos_userbundle
                oauth_user_provider:
#                    service: hwi_oauth.user.provider.fosub_bridge
                    service: gallery_app.user_provider

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/hello/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
