gallery_app_homepage:
    path:     /hello/{name}
    defaults: { _controller: GalleryAppBundle:Default:index }

gallery_app_index:
    path:     /
    defaults: { _controller: GalleryAppBundle:Default:index, name: 'name' }

gallery_app_test:
    path:     /test
    defaults: { _controller: GalleryAppBundle:Default:test }

gallery_app.gallery.index:
    path:     /gallery
    defaults: { _controller: GalleryAppBundle:Gallery:index }

gallery_app.gallery.albums:
    path:     /gallery/{parent}
    defaults: { _controller: GalleryAppBundle:Gallery:albums }

gallery_app.gallery.album:
    path:     /gallery/{parent}/{child}
    defaults: { _controller: GalleryAppBundle:Gallery:album }