services:
    gallery_app.service.user_provider:
        class: Gallery\AppBundle\Service\UserProvider
        parent: hwi_oauth.user.provider.fosub_bridge

    gallery_app.service.album_permission_resolver:
        class: Gallery\AppBundle\Service\AlbumPermissionResolver
        arguments:
            - @doctrine.orm.entity_manager